SELECT
   CTP.CLIENT_NUMBER
  ,CTP.TERMINAL_ID
  ,CTP.TMS_REFERENCE_ID
FROM BW3.CIS_TMS_PARAMETERS CTP
  LEFT JOIN BW3.CHT_DEVICE_REQUEST CDR
       ON CTP.TMS_REQUEST = CDR.INDEX_FIELD
       AND CDR.LANGUAGE = 'POR'
   LEFT JOIN BW3.CHT_PROCESSING_STATUS CPS
       ON CTP.STATUS = CPS.INDEX_FIELD
       AND CPS.LANGUAGE = 'POR'
   LEFT JOIN BW3.CHT_TERMINAL_TYPE CTT
       ON CTP.MODEL_CODE = CTT.MODEL_CODE
       AND CTT.LANGUAGE = 'USA'
   LEFT JOIN BW3.CIS_TMS_PARAMETERS UNISTALL
       ON CTP.TERMINAL_ID = UNISTALL.TERMINAL_ID
       AND UNISTALL.TMS_REQUEST = '002'
   WHERE CTP.INSTITUTION_NUMBER = '00000003'
       AND CTP.CLIENT_NUMBER = (SELECT MAX(CLIENT_NUMBER) FROM BW3.CIS_CLIENT_DETAILS WHERE TRADE_NAME = 'Automation_Boarding' AND  INSTITUTION_NUMBER = '00000003')
       AND CTP.RECORD_DATE =   (SELECT MAX(RECORD_DATE) FROM BW3.CIS_TMS_PARAMETERS WHERE CLIENT_NUMBER = CTP.CLIENT_NUMBER AND  INSTITUTION_NUMBER = '00000003')